name: GitHub Actions Demo

on:
  push:

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Show event info
        run: echo "GitHub Actions is working"

      - name: List files in the repository
        run: ls
